CREATE TABLE IF NOT EXISTS Tag (
  id        INTEGER PRIMARY KEY AUTOINCREMENT,
  userId    INTEGER NOT NULL REFERENCES User(id) ON DELETE CASCADE,
  name      TEXT NOT NULL,
  createdAt TEXT NOT NULL,
  UNIQUE(userId, name)
);

CREATE TABLE IF NOT EXISTS NoteTag (
  noteId INTEGER NOT NULL REFERENCES Note(id) ON DELETE CASCADE,
  tagId  INTEGER NOT NULL REFERENCES Tag(id) ON DELETE CASCADE,
  PRIMARY KEY (noteId, tagId)
);
